language: bash
dist: xenial
services: docker
addons:
  apt:
    packages:
      - docker-ce
    update: true
env:
  - CPU=Xeon buildOS=centos-7.4 imageName=dldt+ffmpeg
  - CPU=Xeon buildOS=centos-7.4 imageName=dldt+gst
  - CPU=Xeon buildOS=centos-7.4 imageName=ffmpeg
  - CPU=Xeon buildOS=centos-7.4 imageName=gst
  - CPU=Xeon buildOS=centos-7.4 imageName=nginx+rtmp
  - CPU=Xeon buildOS=centos-7.4 imageName=ospray
  - CPU=Xeon buildOS=centos-7.4 imageName=ospray+mpi+OpenImageIO
  - CPU=Xeon buildOS=centos-7.5 imageName=dldt+ffmpeg
  - CPU=Xeon buildOS=centos-7.5 imageName=dldt+gst
  - CPU=Xeon buildOS=centos-7.5 imageName=ffmpeg
  - CPU=Xeon buildOS=centos-7.5 imageName=gst
  - CPU=Xeon buildOS=centos-7.5 imageName=nginx+rtmp
  - CPU=Xeon buildOS=centos-7.5 imageName=ospray
  - CPU=Xeon buildOS=centos-7.5 imageName=ospray+mpi+OpenImageIO
  - CPU=Xeon buildOS=centos-7.6 imageName=dldt+ffmpeg
  - CPU=Xeon buildOS=centos-7.6 imageName=dldt+gst
  - CPU=Xeon buildOS=centos-7.6 imageName=ffmpeg
  - CPU=Xeon buildOS=centos-7.6 imageName=gst
  - CPU=Xeon buildOS=centos-7.6 imageName=nginx+rtmp
  - CPU=Xeon buildOS=centos-7.6 imageName=ospray
  - CPU=Xeon buildOS=centos-7.6 imageName=ospray+mpi+OpenImageIO
  - CPU=Xeon buildOS=ubuntu-16.04 imageName=dldt+ffmpeg
  - CPU=Xeon buildOS=ubuntu-16.04 imageName=dldt+gst
  - CPU=Xeon buildOS=ubuntu-16.04 imageName=ffmpeg
  - CPU=Xeon buildOS=ubuntu-16.04 imageName=gst
  - CPU=Xeon buildOS=ubuntu-16.04 imageName=nginx+rtmp
  - CPU=Xeon buildOS=ubuntu-16.04 imageName=ospray
  - CPU=Xeon buildOS=ubuntu-16.04 imageName=ospray+mpi+OpenImageIO
  - CPU=Xeon buildOS=ubuntu-18.04 imageName=dldt+ffmpeg
  - CPU=Xeon buildOS=ubuntu-18.04 imageName=dldt+gst
  - CPU=Xeon buildOS=ubuntu-18.04 imageName=ffmpeg
  - CPU=Xeon buildOS=ubuntu-18.04 imageName=gst
  - CPU=Xeon buildOS=ubuntu-18.04 imageName=nginx+rtmp
  - CPU=Xeon buildOS=ubuntu-18.04 imageName=ospray
  - CPU=Xeon buildOS=ubuntu-18.04 imageName=ospray+mpi+OpenImageIO

before_install:
  - docker version
script:
  - &basescript |
    mkdir build && cd build && cmake ..
    cd ${CPU}/${buildOS}/${imageName}
  - make
  - ctest -V

matrix:
  fast_finish: true
  allow_failures: # All images with GST will have GST SVT VP9 test failing. NGINX RTMP tests are not stable
    - name: centos-7.4/ffmpeg+gst+dev
    - env: CPU=Xeon buildOS=centos-7.4 imageName=dldt+gst
    - env: CPU=Xeon buildOS=centos-7.4 imageName=gst
    - env: CPU=Xeon buildOS=centos-7.4 imageName=nginx+rtmp
    - name: centos-7.5/ffmpeg+gst+dev
    - env: CPU=Xeon buildOS=centos-7.5 imageName=dldt+gst
    - env: CPU=Xeon buildOS=centos-7.5 imageName=gst
    - env: CPU=Xeon buildOS=centos-7.5 imageName=nginx+rtmp
    - name: centos-7.6/ffmpeg+gst+dev
    - env: CPU=Xeon buildOS=centos-7.6 imageName=dldt+gst
    - env: CPU=Xeon buildOS=centos-7.6 imageName=gst
    - env: CPU=Xeon buildOS=centos-7.6 imageName=nginx+rtmp
    - name: ubuntu-16.04/ffmpeg+gst+dev
    - env: CPU=Xeon buildOS=ubuntu-16.04 imageName=dldt+gst
    - env: CPU=Xeon buildOS=ubuntu-16.04 imageName=gst
    - env: CPU=Xeon buildOS=ubuntu-16.04 imageName=nginx+rtmp
    - name: ubuntu-18.04/ffmpeg+gst+dev
    - env: CPU=Xeon buildOS=ubuntu-18.04 imageName=dldt+gst
    - env: CPU=Xeon buildOS=ubuntu-18.04 imageName=gst
    - env: CPU=Xeon buildOS=ubuntu-18.04 imageName=nginx+rtmp
  include:
    # centos-7.4 job
    - name: centos-7.4/ffmpeg+gst+dev
      script:
        - *basescript
        - travis_wait 150 ../script/travis_build.sh Xeon/centos-7.4/ffmpeg+gst+dev
        - cd Xeon/centos-7.4/ffmpeg+gst+dev
        - ctest -V
      after_failure:
        - tail --lines=5000 log_Xeon_centos74_ffmpeg_gst_dev.log
    # centos-7.5 job
    - name: centos-7.5/ffmpeg+gst+dev
      script:
        - *basescript
        - travis_wait 150 ../script/travis_build.sh Xeon/centos-7.5/ffmpeg+gst+dev
        - cd Xeon/centos-7.5/ffmpeg+gst+dev
        - ctest -V
      after_failure:
        - tail --lines=5000 log_Xeon_centos75_ffmpeg_gst_dev.log
    # centos-7.6 job
    - name: centos-7.6/ffmpeg+gst+dev
      script:
        - *basescript
        - travis_wait 150 ../script/travis_build.sh Xeon/centos-7.6/ffmpeg+gst+dev
        - cd Xeon/centos-7.6/ffmpeg+gst+dev
        - ctest -V
      after_failure:
        - tail --lines=5000 log_Xeon_centos76_ffmpeg_gst_dev.log
    # ubuntu-16.04 job
    - name: ubuntu-16.04/ffmpeg+gst+dev
      script:
        - *basescript
        - travis_wait 150 ../script/travis_build.sh Xeon/ubuntu-16.04/ffmpeg+gst+dev
        - cd Xeon/ubuntu-16.04/ffmpeg+gst+dev
        - ctest -V
      after_failure:
        - tail --lines=5000 log_Xeon_ubuntu1604_ffmpeg_gst_dev.log
    # ubuntu-18.04 job
    - name: ubuntu-18.04/ffmpeg+gst+dev
      script:
        - *basescript
        - travis_wait 150 ../script/travis_build.sh Xeon/ubuntu-18.04/ffmpeg+gst+dev
        - cd Xeon/ubuntu-18.04/ffmpeg+gst+dev
        - ctest -V
      after_failure:
        - tail --lines=5000 log_Xeon_ubuntu1804_ffmpeg_gst_dev.log
